=== ZakariaRekhla2004/XML_Projet/Database.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element name="database">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="Concours" type="ConcoursType" />
                <xs:element name="Specialites" type="SpecialitesType" />
                <xs:element name="Diplomes" type="DiplomesType" />
                <xs:element name="Candidats" type="CandidatsType" />
                <xs:element name="Candidatures" type="CandidaturesType" />
                <xs:element name="Choixs" type="ChoixsType" />
            </xs:sequence>
        </xs:complexType>
        <!-- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - pramiryKey- - - - - - - - - -
        - - - - - - - - - - - - - - - - -  -->
        <xs:key name="ConcourKey">
            <xs:selector xpath=".//Concour" />
            <xs:field xpath="@ID_Concours" />
        </xs:key>
        <xs:key name="SpecialiteKey">
            <xs:selector xpath=".//Specialite" />
            <xs:field xpath="@ID_Specialite" />
        </xs:key>
        <xs:key name="DiplomeKey">
            <xs:selector xpath=".//Diplome" />
            <xs:field xpath="@ID_Diplome" />
        </xs:key>
        <xs:key name="CandidatKey">
            <xs:selector xpath=".//Candidat" />
            <xs:field xpath="@ID_Candidat" />
        </xs:key>
        <xs:key name="CandidatureKey">
            <xs:selector xpath=".//Candidature" />
            <xs:field xpath="@ID_Candidature" />
        </xs:key>


        <!-- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - forgeinKey- - - - - - - - - -
        - - - - - - - - - - - - - - - - -  -->
        <xs:keyref name="DiplomeType_SpecialiteRef" refer="SpecialiteKey">
            <xs:selector xpath=".//Diplome" />
            <xs:field xpath="@ID_Specialite" />
        </xs:keyref>

        <xs:keyref name="DiplomeType_CandidatRef" refer="CandidatKey">
            <xs:selector xpath=".//Diplome" />
            <xs:field xpath="@ID_Candidat" />
        </xs:keyref>

        <xs:keyref name="CandidatureType_CandidatRef" refer="CandidatKey">
            <xs:selector xpath=".//Candidature" />
            <xs:field xpath="@ID_Candidat" />
        </xs:keyref>

        <xs:keyref name="ChoixType_CandidatureRef" refer="CandidatureKey">
            <xs:selector xpath=".//Choix" />
            <xs:field xpath="@ID_Candidature" />
        </xs:keyref>
        <xs:keyref name="ChoixType_ConcoursRef" refer="ConcourKey">
            <xs:selector xpath=".//Choix" />
            <xs:field xpath="@ID_Concours" />
        </xs:keyref>


    </xs:element>
    <xs:complexType name="ConcoursType">
        <xs:sequence>
            <xs:element name="Concour" type="ConcourType" maxOccurs="unbounded" />
        </xs:sequence>
    </xs:complexType>
    <xs:complexType name="SpecialitesType">
        <xs:sequence>
            <xs:element name="Specialite" type="SpecialiteType" maxOccurs="unbounded" />
        </xs:sequence>
    </xs:complexType>
    <xs:complexType name="DiplomesType">
        <xs:sequence>
            <xs:element name="Diplome" type="DiplomeType" maxOccurs="unbounded" />
        </xs:sequence>
    </xs:complexType>
    <xs:complexType name="CandidatsType">
        <xs:sequence>
            <xs:element name="Candidat" type="CandidatType" maxOccurs="unbounded" />
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="CandidaturesType">
        <xs:sequence>
            <xs:element name="Candidature" type="CandidatureType" maxOccurs="unbounded" />
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="ChoixsType">
        <xs:sequence>
            <xs:element name="Choix" type="ChoixType" maxOccurs="unbounded" />
        </xs:sequence>
    </xs:complexType>


    <!--        - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -Table- - - - - - - - - - - - - -
    - - - - - - - - -->
    <!--    table de Concours   -->
    <xs:complexType name="ConcourType">

        <xs:sequence>
            <xs:element name="NomConcours" type="xs:string" />
            <xs:element name="DateConcours" type="xs:string" />
            <xs:element name="LieuConcours" type="xs:string" />
        </xs:sequence>
        <xs:attribute name="ID_Concours" type="xs:int" use="required" />
    </xs:complexType>

    <!--    table de Diplome  -->
    <xs:complexType name="DiplomeType">
        <xs:sequence>
            <xs:element name="AnneeObtention" type="xs:int" />
        </xs:sequence>
        <xs:attribute name="ID_Diplome" type="xs:int" use="required" />
        <xs:attribute name="ID_Specialite" type="xs:int" use="required" />
        <xs:attribute name="ID_Candidat" type="xs:int" use="required" />
    </xs:complexType>
    <!-- table specialite -->
    <xs:complexType name="SpecialiteType">

        <xs:sequence>
            <!--<xs:element
            name="ID_Specialite" type="xs:int"/>-->
            <xs:element name="libelle" type="xs:string" />
        </xs:sequence>
        <xs:attribute name="ID_Specialite" type="xs:int" use="required" />
    </xs:complexType>
    <!-- //table Candidat-->
    <xs:complexType name="CandidatType">


        <xs:sequence>
            <!--            <xs:element name="ID_Candidat" type="xs:int"/> -->
            <!--<xs:element
            name="cin" type="xs:string"/>-->
            <!--<xs:element
            name="cne" type="xs:string"/>-->
            <xs:element name="Nom" type="xs:string" />
            <xs:element name="Prenom" type="xs:string" />
            <xs:element name="email" type="xs:string" />
            <xs:element name="password" type="xs:string" />
            <xs:element name="telephone" type="xs:integer" />
            <xs:element name="DateNaissance" type="xs:date" />
            <!-- <xs:element name="ID_Diplome" type="xs:int"/>-->
        </xs:sequence>
        <xs:attribute name="ID_Candidat" type="xs:int" use="required" />
        <xs:attribute name="cin" type="xs:string" use="required" />
        <xs:attribute name="cne" type="xs:string" use="required" />

    </xs:complexType>
    <!--    // table Candidature -->
    <xs:complexType name="CandidatureType">
        <xs:sequence>
            <!--            <xs:element name="ID_Candidature" type="xs:int"/>
-->
            <xs:element name="Date_Candidature" type="xs:date" />
            <!--<xs:element
            name="ID_Candidat" type="xs:int"/>-->
        </xs:sequence>
        <xs:attribute name="ID_Candidature" type="xs:int" use="required" />
        <xs:attribute name="ID_Candidat" type="xs:int" use="required" />

    </xs:complexType>
    <!--///
    table choix  porteuse entre   Candidature et concours -->
    <xs:complexType name="ChoixType">

        <xs:sequence>
            <!--      <xs:element name="ID_Candidature" type="xs:int"/>
            <xs:element name="ID_Concours" type="xs:int"/>-->
            <xs:element name="Priorite" type="xs:int" />
        </xs:sequence>
        <xs:attribute name="ID_Candidature" type="xs:int" use="required" />
        <xs:attribute name="ID_Concours" type="xs:int" use="required" />
    </xs:complexType>

</xs:schema>

=== ZakariaRekhla2004/XML_Projet/DataBase.xml
<?xml version="1.0" encoding="UTF-8"?>
<database xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:noNamespaceSchemaLocation="Database.xsd">
    <Concours>
        <Concour ID_Concours="1">
            <NomConcours>Programming Competition</NomConcours>
            <DateConcours>2023-01-01</DateConcours>
            <LieuConcours>Virtual</LieuConcours>
        </Concour>

        <Concour ID_Concours="2">
            <NomConcours>Math Olympiad</NomConcours>
            <DateConcours>2023-02-15</DateConcours>
            <LieuConcours>In-person</LieuConcours>
        </Concour>

        <Concour ID_Concours="3">
            <NomConcours>Science Fair</NomConcours>
            <DateConcours>2023-03-10</DateConcours>
            <LieuConcours>Hybrid</LieuConcours>
        </Concour>


    </Concours>


    <Specialites>
        <Specialite ID_Specialite="1">
            <libelle>Computer Science</libelle>
        </Specialite>
        <Specialite ID_Specialite="2">
            <libelle>Electrical Engineering</libelle>
        </Specialite>

        <Specialite ID_Specialite="3">
            <libelle>Mechanical Engineering</libelle>
        </Specialite>
    </Specialites>

    <Diplomes>
        <Diplome ID_Diplome="1" ID_Specialite="1" ID_Candidat="1">
            <AnneeObtention>2022</AnneeObtention>
        </Diplome>

        <Diplome ID_Diplome="2" ID_Specialite="2" ID_Candidat="2">
            <AnneeObtention>2023</AnneeObtention>
        </Diplome>

        <Diplome ID_Diplome="3" ID_Specialite="3" ID_Candidat="3">
            <AnneeObtention>2021</AnneeObtention>
        </Diplome>
    </Diplomes>

    <Candidats>
        <Candidat ID_Candidat="1" cin="123456789" cne="987654321">
            <Nom>John</Nom>
            <Prenom>Doe</Prenom>
            <email>john.doe@example.com</email>
            <password>securepassword</password>
            <telephone>1234567890</telephone>
            <DateNaissance>1990-01-01</DateNaissance>
        </Candidat>

        <Candidat ID_Candidat="2" cin="987654321" cne="123456789">
            <Nom>Jane</Nom>
            <Prenom>Smith</Prenom>
            <email>jane.smith@example.com</email>
            <password>anotherpassword</password>
            <telephone>9876543210</telephone>
            <DateNaissance>1988-05-15</DateNaissance>
        </Candidat>

        <Candidat ID_Candidat="3" cin="555555555" cne="111111111">
            <Nom>Alice</Nom>
            <Prenom>Johnson</Prenom>
            <email>alice.johnson@example.com</email>
            <password>securepassword123</password>
            <telephone>5555555555</telephone>
            <DateNaissance>1995-08-20</DateNaissance>
        </Candidat>
    </Candidats>
    <Candidatures>
        <Candidature ID_Candidature="1" ID_Candidat="1">
            <Date_Candidature>2023-01-15</Date_Candidature>
        </Candidature>

        <Candidature ID_Candidature="2" ID_Candidat="2">
            <Date_Candidature>2023-02-28</Date_Candidature>
        </Candidature>

        <Candidature ID_Candidature="3" ID_Candidat="3">
            <Date_Candidature>2023-03-20</Date_Candidature>
        </Candidature>
    </Candidatures>

    <Choixs>
        <Choix ID_Candidature="1" ID_Concours="1">
            <Priorite>1</Priorite>
        </Choix>
        <Choix ID_Candidature="1" ID_Concours="2">
            <Priorite>2</Priorite>
        </Choix>

        <Choix ID_Candidature="1" ID_Concours="3">
            <Priorite>3</Priorite>
        </Choix>
        <Choix ID_Candidature="3" ID_Concours="2">
            <Priorite>2</Priorite>
        </Choix>
    </Choixs>
</database>
